### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by de-finnik** [de-finnik/cuddly-waffle#1]
- [x] Change youtube-dl auto update and get rid of disposable
- [x] add downloading tracks to list (with help of progress callback from youtubedl-android)
- [x] implement previous and next buttons
- [x] click on notification -> open playeractivity
- [ ] fix ServiceExceptionLeaked
- [ ] implement interaction between musicplayerview and playeractivity via swiping
- [ ] work with coroutine in order to handle background api calls and ui thread (e.g update youtube-dl after confirmation when new version is available)
